# Default configuration for Polaris Localization Algorithm

# Processing parameters
processing:
  target_frequency: 30.0  # Hz
  interpolation_method: "linear"
  outlier_threshold: 3.0  # standard deviations

# EKF parameters
ekf:
  dt: 0.033333  # 1/30 seconds
  process_noise: 0.01
  imu_noise: 0.1
  gps_noise: 1.0
  odom_noise: 0.5

# Sensor topics
sensors:
  imu_topics:
    - "/vectornav/imu"
  gps_topics:
    - "/vectornav/gnss"
  pose_topics:
    - "/vectornav/pose"
  control_topics:
    - "/pacmod/accel_rpt"
    - "/pacmod/steering_rpt"
    - "/pacmod/brake_rpt"
    - "/pacmod/vehicle_speed_rpt"

# Output settings
output:
  save_plots: true
  plot_format: "png"
  plot_dpi: 300
  save_results: true
  results_format: "csv"
