name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    
    - name: Run unit tests
      run: |
        python tests/unit_tests.py
    
    - name: Run EKF component tests
      run: |
        python tests/test_ekf_components.py
    
    - name: Check code style
      run: |
        pip install flake8
        flake8 polaris_autonomous_system --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 polaris_autonomous_system --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  validation:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    
    - name: Run EKF validation
      run: |
        python scripts/validate_ekf.py
    
    - name: Upload validation results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: validation-results
        path: results/ekf_validation/

